version: '3.8'
services:
  jasper-reports-api:
    image: registry.gitlab.com/a.galal7/jasper-reports-api:0.1
    volumes:
      - ./src/test/resources/test-reports:/var/reports
    environment:
      SPRING_PROFILES_ACTIVE: security-off
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:12.10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data

networks:
  default:
    driver: bridge

volumes:
  pgdata:
